services:
    postgres:
        image: postgres:latest
        container_name: library_postgres
        environment:
            POSTGRES_USER: lib_admin
            POSTGRES_PASSWORD: lib_password
            POSTGRES_DB: library_management
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
        driver: local
